name = "CNMC Geopol Fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a3b904226fc36ece7ce0d115aae6f2a39bec876c05aab0b5839c87a21ec6a8d"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
