name = "CNMC Geopol Fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22a372ab9970218cf208f4f2673a1e1856f24a18691fb9703925f13e1ddbdbc0"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
