name = "CNMC Geopol Fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e9671750dd3cce83b3ce36ac002a8dc99fd422f8b0c97663c596b1911bd9d41"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
